package main

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"flag"
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"dxps/internal/pki"
)

func runtimeDir() string {
	if v := os.Getenv("DXPS_RUNTIME"); v != "" {
		return v
	}
	h, _ := os.UserHomeDir()
	return filepath.Join(h, "dxps-runtime")
}

func randToken(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	return base64.RawURLEncoding.EncodeToString(b)
}

func dsn(user, pass, db, caFile string) string {
	u := url.URL{Scheme: "postgres", User: url.UserPassword(user, pass), Host: "localhost:5433", Path: "/" + db}
	q := url.Values{}
	q.Set("sslmode", "verify-full")
	q.Set("sslrootcert", filepath.ToSlash(caFile))
	q.Set("application_name", "dxps")
	u.RawQuery = q.Encode()
	return u.String()
}

// cmdSecrets writes runtime/secrets.env once (never overwrites, never prints values).
func cmdSecrets(args []string) error {
	fs := flag.NewFlagSet("secrets", flag.ExitOnError)
	rt := fs.String("runtime", runtimeDir(), "runtime directory")
	fs.Parse(args)
	path := filepath.Join(*rt, "secrets.env")
	if _, err := os.Stat(path); err == nil {
		fmt.Println("secrets: exists", path)
		return nil
	}
	if err := os.MkdirAll(*rt, 0o700); err != nil {
		return err
	}
	ca := filepath.Join(*rt, "pki", "ca.crt")
	pw := map[string]string{
		"super": randToken(24), "owner": randToken(24), "app": randToken(24), "ops": randToken(24),
	}
	lines := []string{
		"# DxPS local runtime secrets - generated by dxpsctl; do not commit or share",
		"DXPS_JWT_KEY=" + randToken(32),
		"DXPS_MASTER_KEY=" + randToken(32),
		"PG_SUPER_PASSWORD=" + pw["super"],
		"PG_OWNER_PASSWORD=" + pw["owner"],
		"PG_APP_PASSWORD=" + pw["app"],
		"PG_OPS_PASSWORD=" + pw["ops"],
		"DXPS_PG_OWNER_DSN=" + dsn("dxps_owner", pw["owner"], "dxps", ca),
		"DXPS_PG_APP_DSN=" + dsn("dxps_app", pw["app"], "dxps", ca),
		"DXPS_PG_OPS_DSN=" + dsn("dxps_ops", pw["ops"], "dxps", ca),
		"DXPS_PG_SUPER_DSN=" + dsn("postgres", pw["super"], "postgres", ca),
	}
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		return err
	}
	fmt.Println("secrets: written", path)
	return nil
}

// cmdCerts creates the dev CA and service certificates in runtime/pki (idempotent).
func cmdCerts(args []string) error {
	fs := flag.NewFlagSet("certs", flag.ExitOnError)
	rt := fs.String("runtime", runtimeDir(), "runtime directory")
	force := fs.Bool("force", false, "regenerate")
	fs.Parse(args)
	dir := filepath.Join(*rt, "pki")
	caCrt, caKey := filepath.Join(dir, "ca.crt"), filepath.Join(dir, "ca.key")
	var ca *pki.CA
	if c, err := os.ReadFile(caCrt); err == nil && !*force { // #nosec G304 -- operator CLI flag
		k, err := os.ReadFile(caKey) // #nosec G304 -- operator CLI flag
		if err != nil {
			return err
		}
		if ca, err = pki.LoadCA(c, k); err != nil {
			return err
		}
	} else if err == nil || errors.Is(err, os.ErrNotExist) {
		if ca, err = pki.NewCA("DxPS Dev Root CA", 5*365*24*time.Hour); err != nil {
			return err
		}
		kp, err := ca.KeyPEM()
		if err != nil {
			return err
		}
		if err := pki.WriteBundle(dir, "ca", &pki.Bundle{CertPEM: ca.CertPEM, KeyPEM: kp}); err != nil {
			return err
		}
	} else {
		return err
	}
	local := []net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")}
	leaves := []pki.LeafOpts{
		{CommonName: "postgres", DNS: []string{"localhost"}, IPs: local, Server: true},
		{CommonName: "gateway", DNS: []string{"localhost", "gateway.dxps.local"}, IPs: local, Server: true},
		{CommonName: "netsim", DNS: []string{"localhost", "nrf.5gc.local", "udr.5gc.local"}, IPs: local, Server: true},
		{CommonName: "adapter", Client: true},
		{CommonName: "eventhub", Client: true},
	}
	for _, l := range leaves {
		if _, err := os.Stat(filepath.Join(dir, l.CommonName+".crt")); err == nil && !*force {
			continue
		}
		b, err := ca.Issue(l)
		if err != nil {
			return err
		}
		if err := pki.WriteBundle(dir, l.CommonName, b); err != nil {
			return err
		}
	}
	fmt.Println("certs: ok", dir)
	return nil
}
