package gateway

import (
	"encoding/json"
	"time"
)

// TMF641 v5 ServiceOrder subset accepted by DxPS. Unknown fields are rejected.
type ServiceOrderReq struct {
	Type                    string       `json:"@type,omitempty"`
	BaseType                string       `json:"@baseType,omitempty"`
	SchemaLocation          string       `json:"@schemaLocation,omitempty"`
	ExternalID              string       `json:"externalId,omitempty"`
	Priority                string       `json:"priority,omitempty"`
	Category                string       `json:"category,omitempty"`
	Description             string       `json:"description,omitempty"`
	RequestedStartDate      *time.Time   `json:"requestedStartDate,omitempty"`
	RequestedCompletionDate *time.Time   `json:"requestedCompletionDate,omitempty"`
	Channel                 []ChannelRef `json:"channel,omitempty"`
	ServiceOrderItem        []OrderItem  `json:"serviceOrderItem"`
}

type ChannelRef struct {
	Type string `json:"@type,omitempty"`
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Role string `json:"role,omitempty"`
}

type OrderItem struct {
	Type                         string             `json:"@type,omitempty"`
	ID                           string             `json:"id"`
	Action                       string             `json:"action"`
	Quantity                     int                `json:"quantity,omitempty"`
	Service                      ServiceRefOrValue  `json:"service"`
	ServiceOrderItemRelationship []ItemRelationship `json:"serviceOrderItemRelationship,omitempty"`
	State                        string             `json:"state,omitempty"`
}

type ServiceRefOrValue struct {
	Type                  string           `json:"@type,omitempty"`
	ID                    string           `json:"id,omitempty"`
	Name                  string           `json:"name,omitempty"`
	ServiceSpecification  SpecRef          `json:"serviceSpecification"`
	ServiceCharacteristic []Characteristic `json:"serviceCharacteristic,omitempty"`
}

type SpecRef struct {
	Type    string `json:"@type,omitempty"`
	ID      string `json:"id"`
	Name    string `json:"name,omitempty"`
	Version string `json:"version,omitempty"`
}

type Characteristic struct {
	Type      string          `json:"@type,omitempty"`
	Name      string          `json:"name"`
	ValueType string          `json:"valueType,omitempty"`
	Value     json.RawMessage `json:"value"`
}

type ItemRelationship struct {
	Type             string  `json:"@type,omitempty"`
	RelationshipType string  `json:"relationshipType"`
	OrderItem        ItemRef `json:"orderItem"`
}

type ItemRef struct {
	Type   string `json:"@type,omitempty"`
	ItemID string `json:"itemId"`
}

// ServiceOrder is the TMF641 response representation.
type ServiceOrder struct {
	Type             string         `json:"@type"`
	ID               string         `json:"id"`
	Href             string         `json:"href"`
	ExternalID       string         `json:"externalId,omitempty"`
	Priority         string         `json:"priority"`
	Category         string         `json:"category,omitempty"`
	State            string         `json:"state"`
	OrderDate        time.Time      `json:"orderDate"`
	CompletionDate   *time.Time     `json:"completionDate,omitempty"`
	ServiceOrderItem []OrderItem    `json:"serviceOrderItem"`
	ErrorMessage     []ErrorMessage `json:"errorMessage,omitempty"`
}

type ErrorMessage struct {
	Type    string `json:"@type"`
	Code    string `json:"code"`
	Reason  string `json:"reason"`
	Message string `json:"message,omitempty"`
}

// TMF630 error.
type APIError struct {
	Type    string `json:"@type"`
	Code    string `json:"code"`
	Reason  string `json:"reason"`
	Message string `json:"message,omitempty"`
	Status  string `json:"status"`
}

type CancelReq struct {
	Type               string      `json:"@type,omitempty"`
	CancellationReason string      `json:"cancellationReason,omitempty"`
	ServiceOrder       OrderRefReq `json:"serviceOrder"`
}

type OrderRefReq struct {
	Type string `json:"@type,omitempty"`
	ID   string `json:"id"`
	Href string `json:"href,omitempty"`
}

// TMF688 hub registration.
type HubReq struct {
	Callback string `json:"callback"`
	Query    string `json:"query,omitempty"`
	Secret   string `json:"secret,omitempty"`
}

type HubResp struct {
	ID       string `json:"id"`
	Callback string `json:"callback"`
	Query    string `json:"query,omitempty"`
	Secret   string `json:"secret,omitempty"` // returned once when generated by DxPS
}
